// src/components/Game.tsx
import React, { useState } from 'react'
import styled from 'styled-components/macro'

import Deck from './Deck'
import Stats from './Stats'
import { SwipeDirection } from '../util/constants'
import { GameScenario } from '../game/GameScenario'
import { CardData, EventCard } from '../game/ContentTypes'
import { GameState } from '../game/GameTypes'

const Footer = styled.footer`
    display: flex;
    justify-content: center;
    align-items: center;
`

type GameProps = {
    scenario: GameScenario
}

const Game: React.FunctionComponent<GameProps> = ({ scenario }) => {
    const [state, setState] = useState<GameState>(scenario.getInitialState())

    const card = addUniqueCardId(state.card)
    const worldState = state.world.state
    const stats = scenario.stats.map((stat) =>
        Object.assign({}, stat, {
            value: worldState[stat.id],
        }),
    )

    function onSwipe(
        card: CardData | EventCard,
        direction: SwipeDirection,
    ): void {
        const action =
            direction === SwipeDirection.Left
                ? card.actions.left
                : card.actions.right

        setState(scenario.getUpdatedState(state, card, action))
    }

    return (
        <>
            <Stats stats={stats} />
            <Deck onSwipe={onSwipe} card={card} tick={state.rounds} />
            <Footer>
                <div className="time-remaining"></div>
            </Footer>
        </>
    )
}

function addUniqueCardId(
    card: CardData | EventCard,
    index: number = 0,
): (CardData | EventCard) & { id: string } {
    return {
        ...card,
        id: Date.now() + ':' + index,
    }
}

export default Game

// web/src/components/Game.svelte
<script lang="ts" context="module">
    import { writable } from 'svelte/store'

    import CardView from '$components/CardView.svelte'
    import Stats from '$components/Stats.svelte'
    import { SwipeDirection } from '$util/constants'
    import type { GameState, Game as GameLogic, Stat } from '$game/Types'
    import { onMount } from 'svelte'
</script>

<script lang="ts">
    export let game: GameLogic<any>

    const state = writable<GameState<any>>(game.initialState)

    let stats: Array<Stat<any> & { value: number }>

    $: {
        stats = game.stats.map((stat) =>
            Object.assign({}, stat, {
                value: stat.getValue($state),
            }),
        )
    }

    function onSwipe(direction: SwipeDirection) {
        const action =
            direction === SwipeDirection.Left
                ? $state.card.actions.left.modifier
                : $state.card.actions.right.modifier

        $state = game.applyAction($state, action)
    }

    function noop(e: Event) {
        e.preventDefault()
        e.stopPropagation()
        return false
    }

    onMount(() => {
        document.documentElement.classList.add('in-game')
        return () => document.documentElement.classList.remove('in-game')
    })
</script>

<main class="text-white" on:dragstart={noop} on:select={noop}>
    <Stats {stats} />

    {#if $state.card}
        <CardView card={$state.card} {onSwipe} />
    {/if}
</main>
